"""Outreach email design templates (best-practice color systems)."""

from __future__ import annotations

from typing import Any

# Each theme uses high-contrast text, clear CTA, and a calm page background.
EMAIL_TEMPLATES: dict[str, dict[str, Any]] = {
    "midnight_teal": {
        "id": "midnight_teal",
        "name": "Midnight Teal",
        "blurb": "Dark card, teal CTA, high contrast",
        "page_bg": "#0c1118",
        "card_bg": "#172231",
        "card_border": "#2a3a4f",
        "text": "#eef3f8",
        "muted": "#8fa0b5",
        "body": "#c5d0dc",
        "eyebrow": "#3d9a7a",
        "heading": "#eef3f8",
        "cta_bg": "#3d9a7a",
        "cta_text": "#04110c",
        "link": "#c4a35a",
        "swatches": ["#0c1118", "#172231", "#3d9a7a", "#c4a35a"],
    },
    "clean_white": {
        "id": "clean_white",
        "name": "Clean White",
        "blurb": "Classic light inbox-friendly layout",
        "page_bg": "#f4f6f8",
        "card_bg": "#ffffff",
        "card_border": "#e2e8f0",
        "text": "#0f172a",
        "muted": "#64748b",
        "body": "#334155",
        "eyebrow": "#0f766e",
        "heading": "#0f172a",
        "cta_bg": "#0f766e",
        "cta_text": "#ffffff",
        "link": "#0f766e",
        "swatches": ["#f4f6f8", "#ffffff", "#0f766e", "#334155"],
    },
    "navy_corporate": {
        "id": "navy_corporate",
        "name": "Navy Corporate",
        "blurb": "Traditional B2B trust palette",
        "page_bg": "#e8eef5",
        "card_bg": "#ffffff",
        "card_border": "#c5d4e8",
        "text": "#0b1f3a",
        "muted": "#5b6f88",
        "body": "#243b53",
        "eyebrow": "#1e3a5f",
        "heading": "#0b1f3a",
        "cta_bg": "#1e3a5f",
        "cta_text": "#ffffff",
        "link": "#1d4ed8",
        "swatches": ["#e8eef5", "#ffffff", "#1e3a5f", "#1d4ed8"],
    },
    "forest_trust": {
        "id": "forest_trust",
        "name": "Forest Trust",
        "blurb": "Growth and reliability greens",
        "page_bg": "#eef6f0",
        "card_bg": "#ffffff",
        "card_border": "#cfe3d4",
        "text": "#14261a",
        "muted": "#5f7464",
        "body": "#2f4636",
        "eyebrow": "#2f6b3c",
        "heading": "#14261a",
        "cta_bg": "#2f6b3c",
        "cta_text": "#ffffff",
        "link": "#1f5c32",
        "swatches": ["#eef6f0", "#ffffff", "#2f6b3c", "#14261a"],
    },
    "slate_minimal": {
        "id": "slate_minimal",
        "name": "Slate Minimal",
        "blurb": "Quiet gray, sharp CTA",
        "page_bg": "#eef0f3",
        "card_bg": "#ffffff",
        "card_border": "#d5dae3",
        "text": "#111827",
        "muted": "#6b7280",
        "body": "#374151",
        "eyebrow": "#4b5563",
        "heading": "#111827",
        "cta_bg": "#111827",
        "cta_text": "#ffffff",
        "link": "#2563eb",
        "swatches": ["#eef0f3", "#ffffff", "#111827", "#2563eb"],
    },
    "sand_warm": {
        "id": "sand_warm",
        "name": "Sand Warm",
        "blurb": "Warm paper tone, earthy CTA",
        "page_bg": "#f3eee6",
        "card_bg": "#fffcf7",
        "card_border": "#e4d8c4",
        "text": "#2a2118",
        "muted": "#7a6a56",
        "body": "#4a3c2e",
        "eyebrow": "#9a6b3f",
        "heading": "#2a2118",
        "cta_bg": "#9a6b3f",
        "cta_text": "#fffaf3",
        "link": "#8a5a30",
        "swatches": ["#f3eee6", "#fffcf7", "#9a6b3f", "#2a2118"],
    },
    "ocean_clear": {
        "id": "ocean_clear",
        "name": "Ocean Clear",
        "blurb": "Friendly blue SaaS look",
        "page_bg": "#eaf4fb",
        "card_bg": "#ffffff",
        "card_border": "#c5dff0",
        "text": "#0c2a3d",
        "muted": "#5a7386",
        "body": "#1f4158",
        "eyebrow": "#0284c7",
        "heading": "#0c2a3d",
        "cta_bg": "#0284c7",
        "cta_text": "#ffffff",
        "link": "#0369a1",
        "swatches": ["#eaf4fb", "#ffffff", "#0284c7", "#0c2a3d"],
    },
    "charcoal_gold": {
        "id": "charcoal_gold",
        "name": "Charcoal Gold",
        "blurb": "Premium dark with gold accents",
        "page_bg": "#121212",
        "card_bg": "#1c1c1c",
        "card_border": "#333333",
        "text": "#f5f5f4",
        "muted": "#a8a29e",
        "body": "#d6d3d1",
        "eyebrow": "#d4a017",
        "heading": "#fafaf9",
        "cta_bg": "#d4a017",
        "cta_text": "#1a1405",
        "link": "#e8c547",
        "swatches": ["#121212", "#1c1c1c", "#d4a017", "#f5f5f4"],
    },
    "coral_signal": {
        "id": "coral_signal",
        "name": "Coral Signal",
        "blurb": "Bright CTA on clean white",
        "page_bg": "#f7f4f2",
        "card_bg": "#ffffff",
        "card_border": "#eadfd8",
        "text": "#1c1917",
        "muted": "#78716c",
        "body": "#44403c",
        "eyebrow": "#e11d48",
        "heading": "#1c1917",
        "cta_bg": "#e11d48",
        "cta_text": "#ffffff",
        "link": "#be123c",
        "swatches": ["#f7f4f2", "#ffffff", "#e11d48", "#1c1917"],
    },
    "ink_paper": {
        "id": "ink_paper",
        "name": "Ink on Paper",
        "blurb": "Editorial black and cream",
        "page_bg": "#f7f3ea",
        "card_bg": "#fffdf8",
        "card_border": "#e7dfd0",
        "text": "#171412",
        "muted": "#6f675c",
        "body": "#3b342c",
        "eyebrow": "#171412",
        "heading": "#171412",
        "cta_bg": "#171412",
        "cta_text": "#fffdf8",
        "link": "#1d4ed8",
        "swatches": ["#f7f3ea", "#fffdf8", "#171412", "#1d4ed8"],
    },
}

DEFAULT_TEMPLATE_ID = "midnight_teal"


def list_email_templates() -> list[dict[str, Any]]:
    return [
        {
            "id": t["id"],
            "name": t["name"],
            "blurb": t["blurb"],
            "swatches": t["swatches"],
        }
        for t in EMAIL_TEMPLATES.values()
    ]


def get_email_template(template_id: str | None) -> dict[str, Any]:
    key = (template_id or "").strip() or DEFAULT_TEMPLATE_ID
    return EMAIL_TEMPLATES.get(key) or EMAIL_TEMPLATES[DEFAULT_TEMPLATE_ID]
